# Generated by Django 4.2.7 on 2025-07-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='message_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
