# Generated by Django 4.2.7 on 2025-07-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_wallet_message_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='message_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
